---
kind: pipeline
name: build-image

platform:
  os: linux
  arch: amd64

steps:
- name: docker-image
  pull: never
  image: docker.io/dominikschmidt/drone-docker:latest
  commands:
  - docker version;
  - docker info;
  - /usr/local/bin/dockerd-entrypoint.sh /bin/drone-docker

  settings:
    daemon_off: true
    dockerfile: Dockerfile
    dry_run: true
    repo: ubuntu_test

  environment:
    DOCKER_BUILDKIT: 1
    PLUGIN_PULL_IMAGE: false
    PLUGIN_PURGE: false
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

trigger:
  event:
  - promote
  - rollback
  target:
  - build-image
