FROM kdeneon/plasma:user-lts

USER root

RUN apt-get install -y qt5-default ninja-build cmake build-essential qtbase5-dev

WORKDIR /
RUN install -d qdirtest
COPY qdirtest/ /qdirtest/

WORKDIR /qdirtest
CMD /qdirtest/test.sh
